### ISSUE TITLE
Adding alternative keywords

### ISSUE THREAD

**Issue by LyesSaadi** [azizamari/Ncodi#59]
"Facebook" Tunisian as I like to name it, aka, Tunisian written with Latin characters and Arabic numerals is not set in stone, and no dictionary exists to define how to write some words. And thus, some regional, and personal, differences exists. For example, I sometime write "kan", "ken" and "madem", "madam" and "ghalet", "ghalat" and "raje3", "raja3"... etc...

So, I want to ask you how open would you be to implementing those alternative ways to write those keywords?

And I guess this issue could be dedicated to collect them in order to make it more comfortable for everyone to use Ncodi.

Obviously, this comes with drawbacks. Indeed, a programming language has advantages in having a consistent and set in stone way to write keywords. Allowing those alternatives would open the gate to a hell of a mess every time there's a project with multiple people in it, or even with only one person writing a word a different way each day. And inconsistencies do threaten readability and makes a syntax more fragile (and restricts even more available variable names).

**Comment by azizamari** [comment]
I wrote ncodi with that in my. The syntax is easily extensible I can even add support to 10 languages in minutes (fun fact: currently it also supports english keywords like if, for, else,...) Check #52
