### ISSUE TITLE
Use constants instead of hard coded numbers

### ISSUE THREAD

**Issue by atefBB** [azizamari/Ncodi#60]
https://github.com/azizamari/Ncodi/blob/47bca33fa426d5d5fbcb980b84385e6140c7c293/src/Ncodi/CodeAnalysis/Syntax/SyntaxFacts.cs#L16
In the line above, you can use `constants` instead of `hard coded numbers` which has no meaning, what is the meaning of 6 or 0 numbers here? 
Doing so, the code will be more readable for others new devs.

**Comment by azizamari** [comment]
That's the precedence order. I use it to add priority to my code and arithmetic operations . If i remove it 
3+2*5 will return 25(5*5) instead of 30(3*10)

**Comment by azizamari** [comment]
As u can see star token "*" /multiplication has a higher precedence thsn minusToken or plusToken (addition and subtraction)

**Comment by atefBB** [comment]
I'm not saying to remove them, simply replace `hard coded numbers` with `constants`.
Example in `js` (because I don't know how to define constant in C#):
const HIGH_PRIORITY = 6; // and simply use `HIGH_PRIORITY` in your code
